# -*- coding: utf-8 -*-
"""plot_2a

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lofW797w5KiBUhHKDFwTC3_AsDY2x_eY
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import scipy as sci

#Me tocó aumentar en uno a Nsteps
Nsteps=1000

xdata=np.zeros(Nsteps)
ydata=np.zeros(Nsteps)

f = open('datos_a.dat', 'r')
i=0
for line in f:
    line = line.strip()
    columns = line.split()
    xdata[i] = float(columns[0])
    ydata[i] = float(columns[1])
    i+=1
f.close()


fig = plt.figure(figsize=(17, 10.5))
plt.title('Solución de ecuación diferencial por RK4', fontsize=20)
plt.xlabel('$r$', fontsize=15)
plt.ylabel('$R(r)$', fontsize=15)

plt.plot(xdata,ydata)

plt.savefig('Grafica_2a.png')
plt.close()